// AUTO-GENERATED by sync_blog_index.py -- do not edit by hand.
// Source of truth: AU/blog.html ARTICLES array (updated by _update_articles.py on each publish).
window.BLOG_ARTICLES =             {
      slug: 'senior-dog-kidney-ageing-normal-vs-disease',
      title: 'Senior Dog Kidney Ageing: Normal Change or Kidney Disease?',
      category: 'kidney',
      excerpt: 'Learn why age alone cannot diagnose kidney disease in a senior dog, which changes matter, and how blood, urine and blood-pressure trends fit together.',
      date: '09 Aug 2026',
      readTime: '14 min',
      img: 'https://images.pexels.com/photos/1805160/pexels-photo-1805160.jpeg?auto=compress&cs=tinysrgb&w=800',
      pinned: false
    },
    {
      slug: 'senior-dog-heart-ageing-normal-vs-disease',
      title: 'Senior Dog Heart Ageing: Normal Change or Heart Disease?',
      category: 'heart',
      excerpt: 'Learn which changes may accompany ageing in a large senior dog, which heart signs need attention, and how vets separate normal change from disease.',
      date: '09 Aug 2026',
      readTime: '13 min',
      img: 'https://images.pexels.com/photos/3335878/pexels-photo-3335878.jpeg?auto=compress&cs=tinysrgb&w=800',
      pinned: false
    },
    {
      slug: 'heart-murmurs-in-senior-dogs',
      title: 'Heart Murmurs in Senior Dogs: What They Mean and When to Act',
      category: 'heart',
      excerpt: 'A heart murmur is a sound, not a diagnosis. Learn what it may mean in a senior dog, which tests clarify the cause, and when to seek urgent care.',
      date: '10 Aug 2026',
      readTime: '12 min',
      img: 'https://images.pexels.com/photos/551628/pexels-photo-551628.jpeg?auto=compress&cs=tinysrgb&w=800',
      pinned: false
    },
{
                slug: 'your-dogs-heart-murmur-what-every-aussie-owner-needs-to-know-about-canine-heart-disease',
                category: 'heart',
                title: 'Your Dog',
                excerpt: 'A heart murmur sounds scary, but understanding what it means can help you make the best decisions for your senior dog',
                date: 'July 26, 2026', readTime: '5 min',
                img: '',
                pinned: false
            },
            {
                slug: 'senior-dog-slow-recovery-after-exercise',
                category: 'heart',
                title: 'Senior Dog Slow After Exercise: Is It the Heart? | PawWell',
                excerpt: 'A senior dog recovering slowly after exercise may need a health check. Learn what to observe, safer walking steps and when breathing or collapse is urgent.',
                date: 'August 6, 2026', readTime: '7 min',
                img: '',
                pinned: false
            },
            {
                slug: 'senior-dog-vomiting-tired-kidney-warning',
                category: 'kidney',
                title: 'Senior Dog Vomiting and Tired: Could It Be Kidneys? | PawWell',
                excerpt: 'Occasional vomiting and tiredness in a senior dog can have many causes. Learn when kidneys may be involved, what to record and when care is urgent.',
                date: 'August 6, 2026', readTime: '7 min',
                img: '',
                pinned: false
            },
            {
                slug: 'osteoarthritis-in-dogs-explained',
                category: 'arthritis',
                title: 'Osteoarthritis in Dogs: More Than Worn-Out Joints | PawWell',
                excerpt: 'Osteoarthritis in dogs is more than simple wear and tear. Learn what changes inside a joint, how pain may appear and how vets build a management plan.',
                date: 'August 6, 2026', readTime: '8 min',
                img: '',
                pinned: false
            },
            {
                slug: 'senior-dog-walking-slower-not-just-age',
                category: 'arthritis',
                title: 'Senior Dog Walking Slower? It May Not Be Just Age',
                excerpt: 'A slower pace is not always just old age. Learn which walking changes in senior dogs signal joint pain, weakness, or other conditions worth a vet check.',
                date: 'August 5, 2026', readTime: '7 min read',
                img: '',
                pinned: false
            },
            {
                slug: 'why-your-senior-dog-may-be-hiding-pain-and-how-to-spot-it',
                category: 'arthritis',
                title: 'Why Your Senior Dog May Be Hiding Pain (and How to Spot It)',
                excerpt: 'Stiffness, slow rising and shorter walks are not just old age. Learn the subtle signs of joint pain in senior dogs and what to do.',
                date: 'August 4, 2026', readTime: '7 min read',
                img: '',
                pinned: false
            },
            {
                slug: 'why-large-senior-dogs-face-more-heart-problems',
                category: 'heart',
                title: 'Why Large Senior Dogs Face More Heart Problems',
                excerpt: 'Large senior dogs face significantly higher heart disease risk. Learn why age and size compound cardiac issues and what signs to watch for.',
                date: 'August 3, 2026', readTime: '9 min read',
                img: '',
                pinned: false
            },
            {
                slug: 'why-large-senior-dogs-develop-joint-problems',
                category: 'arthritis',
                title: 'Why Large Senior Dogs Develop Joint Problems',
                excerpt: 'Joint problems in large senior dogs are common but manageable. Learn the early signs, risk factors and evidence-based ways to keep your dog comfortable.',
                date: 'August 3, 2026', readTime: '8 min read',
                img: '',
                pinned: false
            },
            {
                slug: 'large-senior-dogs-and-kidney-risk',
                category: 'kidney',
                title: 'Large Senior Dogs and Kidney Risk: What Actually Matters?',
                excerpt: 'Kidney disease is a leading health concern for senior dogs. Understand the key risk factors, warning signs and what you can do to protect your dog.',
                date: 'August 3, 2026', readTime: '8 min read',
                img: '',
                pinned: false
            },
            {
                slug: 'cough-and-dry-heave-in-large-senior-dogs-is-it-the-heart',
                category: 'heart',
                title: 'Senior Large-Breed Dog Coughing, Then Dry-Heaving: Could It Be Their Heart?',
                excerpt: 'A cough followed by a gag can be a heart warning in older large breeds. Learn the danger signs and what to do tonight before you call the vet.',
                date: 'August 2, 2026', readTime: '9 min read',
                img: '',
                pinned: false
            },
            {
                slug: 'why-is-my-big-old-dog-suddenly-not-moving-personality-or-pain',
                category: 'Kidney',
                title: 'Why Is My Big Old Dog Suddenly Not Moving? Personality or Pain?',
                excerpt: 'A big old dog that',
                date: 'August 01, 2026', readTime: '6 min',
                img: '',
                pinned: false
            },
            {
                slug: 'senior-large-dog-suddenly-wont-move-read-this-nononsense-checklist-now',
                category: 'Heart',
                title: 'Senior Large Dog Suddenly Won\',
                excerpt: 'If your large senior dog has suddenly stopped wanting to walk, its likely a health issue, not laziness. Learn the warning signs and when to see a vet.',
                date: 'August 01, 2026', readTime: '5 min',
                img: '',
                pinned: false
            },
            {
                slug: 'why-your-large-dogs-bad-breath-and-mouth-sores-might-mean-kidney-worry',
                category: 'Kidney',
                title: 'Why Your Large Dogs Bad Breath and Mouth Sores Might Mean Kidney Worry',
                excerpt: 'Worsening breath and mouth ulcers in a senior large-breed dog could point to kidney trouble. Learn the signs, what to check at home, and when to call the vet.',
                date: 'August 01, 2026', readTime: '6 min',
                img: '',
                pinned: false
            },
            {
                slug: 'purple-gums-in-big-dogs-a-no-nonsense-guide-for-senior-large-breeds',
                category: 'Heart',
                title: 'Purple Gums in Big Dogs: A No-Nonsense Guide for Senior Large Breeds',
                excerpt: 'Purple or blue gums in a Labrador, Rottweiler, or other large breed can signal a heart emergency. Learn what causes it, how to check at home, and when to go to the vet right away.',
                date: 'August 01, 2026', readTime: '5 min',
                img: '',
                pinned: false
            },
            {
                slug: 'your-senior-dogs-limp-more-than-arthritis-a-guide-for-large-breeds',
                category: 'Arthritis',
                title: 'Your Senior Dogs Limp: More Than Arthritis? A Guide for Large Breeds',
                excerpt: 'A limp isnt always arthritis in older large breeds. Learn what else could be causing it, when to worry, and simple at-home checks you can do tonight.',
                date: 'August 01, 2026', readTime: '6 min',
                img: '',
                pinned: false
            },
            {
                slug: 'why-your-senior-dog-coughs-at-night-heart-or-just-a-hack',
                category: 'heart',
                title: 'Why Your Senior Dog Coughs at Night: Heart or Just a Hack?',
                excerpt: 'A night cough in your large senior dog can be a red flag for heart trouble. Learn when to worry, home comfort tips, and how to count sleeping breaths in plain Aussie English.',
                date: 'July 31, 2026', readTime: '6 min',
                img: '',
                pinned: false
            },
            {
                slug: 'what-chronic-kidney-disease-in-large-breeds-really-means-and-why-its-not-kidney-failure',
                category: 'kidney',
                title: 'What Chronic Kidney Disease in Large Breeds Really Means (And Why It\',
                excerpt: 'A warm, chatty guide for Aussie owners: CKD is a staged condition, not immediate kidney failure. Learn what abnormal kidney values really mean and how to help your big dog.',
                date: 'July 31, 2026', readTime: '5 min',
                img: '',
                pinned: false
            },
            {
                slug: 'dog-cough-heart-or-airway-5-clues-to-record-for-your-vet',
                category: 'heart',
                title: 'Dog Cough: Heart or Airway? 5 Clues to Record for Your Vet',
                excerpt: 'Learn to tell if your senior large breed dog',
                date: 'July 31, 2026', readTime: '5 min',
                img: '',
                pinned: false
            },
            {
                slug: 'your-senior-dogs-joint-map-hip-elbow-knee-spinewhats-really-going-on',
                category: 'arthritis',
                title: 'Your Senior Dogs Joint Map: Hip, Elbow, Knee & SpineWhats Really Going On',
                excerpt: 'Learn how different large-breed joint spots (hip, knee, elbow, spine) can show up, from a quiet hip sway to morning stiffness, and simple at-home checks you can do tonight.',
                date: 'July 31, 2026', readTime: '6 min',
                img: '',
                pinned: false
            },
            {
                slug: 'is-your-senior-dog-hiding-toothache-what-poppys-bad-breath-taught-her-aussie-fam',
                category: 'other',
                title: 'Is Your Senior Dog Hiding Toothache? What Poppy&#x27;s Bad Breath Taught Her Aussie Family',
                excerpt: 'Bad breath and avoiding chew toys can be signs of hidden dental pain in senior dogs. Poppy’s story shows what owners should watch for.',
                date: 'July 30, 2026', readTime: '6 min',
                img: '',
                pinned: false
            },
            {
                slug: 'your-dogs-heart-murmur-simple-bedside-checks-that-could-save-their-life',
                category: 'heart',
                title: 'Your Dog&#x27;s Heart Murmur: Simple Bedside Checks That Could Save Their Life',
                excerpt: 'Heart murmurs are graded 1 to 6 in dogs. Learn what each grade means, which tests to ask your vet for, and the simple checks you can do at home to monitor a murmur between visits.',
                date: 'July 29, 2026', readTime: '7 min',
                img: '',
                pinned: false
            },
            {
                slug: 'heart-murmurs-and-doggy-dentals-why-your-pup-can-still-have-a-clean-pain-free-sm',
                category: 'heart',
                title: 'Heart Murmurs and Doggy Dentals: Why Your Pup Can Still Have a Clean, Pain-Free Smile',
                excerpt: 'Many dogs with heart murmurs still need dental work under anaesthetic. Here is how vets assess the risk, what pre-anaesthetic testing looks like, and how to keep your dog safe.',
                date: 'July 29, 2026', readTime: '5 min',
                img: '',
                pinned: false
            },
            {
                slug: 'when-to-worry-about-senior-dog-stiffness',
                category: 'arthritis',
                title: 'When to Worry About Your Senior Dog Stiffness',
                excerpt: 'Occasional stiffness after a long walk or a cold night is common in senior dogs and often eases with a little rest. But some signs should never be...',
                date: 'July 27, 2026', readTime: '4 min',
                img: '',
                pinned: false
            },
            {
                slug: 'early-signs-joint-pain-dogs-how-to-help-your-aussie-mate-stay-active',
                category: 'arthritis',
                title: 'Early Signs of Joint Pain in Dogs and How to Help Your Aussie Mate Stay Active',
                excerpt: 'Occasional stiffness after a long walk or a cold night is common in senior dogs and often eases with a little rest. But some signs should never be ignored.',
                date: 'July 27, 2026', readTime: '4 min',
                img: '',
                pinned: false
            },
            {
                slug: 'when-your-senior-dog-needs-the-vet-for-arthritis',
                category: 'arthritis',
                title: 'When Your Senior Dog Needs the Vet for Arthritis',
                excerpt: 'Occasional stiffness may improve with rest, but certain signs should never be ignored. Learn when arthritis warrants a vet visit.',
                date: 'July 27, 2026', readTime: '4 min',
                img: '',
                pinned: false
            },
            {
                slug: 'increased-thirst-and-urination-early-signs-canine-kidney-disease',
                category: 'kidney',
                title: 'Is Your Senior Dog Drinking More Water Than Usual? Early Kidney Disease Signs',
                excerpt: 'Excessive thirst and frequent urination are the most common early signs of chronic kidney disease in senior dogs — yet they',
                date: 'July 27, 2026', readTime: '5 min',
                img: '',
                pinned: false
            },
            {
                slug: 'kidney-disease-senior-dogs-diet-treatment-complete-guide',
                category: 'kidney',
                title: 'Kidney Disease in Senior Dogs: Your Complete Guide to Diet, Treatment & Survival',
                excerpt: 'A diagnosis of chronic kidney disease does not mean giving up. With the right prescription diet, medical management, and regular monitoring, many senior dogs live comfortably for years. Here',
                date: 'July 27, 2026', readTime: '5 min',
                img: '',
                pinned: false
            },
            {
                slug: 'kidney-biopsy-in-dogs-what-it-reveals-and-why-it-matters',
                category: 'kidney',
                title: 'Kidney Biopsy in Dogs: What It Reveals and Why It Changes Treatment',
                excerpt: 'A kidney biopsy can identify the exact type of kidney disease your dog has — and that information directly determines whether to use immunosuppression, kidney protection, or both. New data from 1,439 canine biopsies explains why it matters.',
                date: 'July 27, 2026', readTime: '5 min',
                img: '',
                pinned: false
            },
            {
                slug: 'is-your-senior-small-dog-coughing-at-night-its-not-just-old-age-could-be-heart',
                category: 'heart',
                title: 'Is Your Senior Small Dog Coughing at Night? It',
                excerpt: 'That soft, hacking cough at night could be more than old age. Learn how coughing relates to heart disease in small breed dogs.',
                date: 'July 26, 2026', readTime: '6 min',
                img: '',
                pinned: false
            },
            {
                slug: '7-silent-signs-senior-dog-heart-needs-check-up-what-to-do-tonight',
                category: 'heart',
                title: '7 Silent Signs Your Senior Dog',
                excerpt: 'Watch for these quiet warning signs that your older dog',
                date: 'July 26, 2026', readTime: '4 min',
                img: '',
                pinned: false
            },
            {
                slug: 'heart-failure-in-dogs-from-silent-belly-bloat-to-deadly-blood-clots',
                category: 'heart',
                title: 'Heart Failure in Dogs: From Silent Belly Bloat to Deadly Blood Clots',
                excerpt: 'One Cavalier',
                date: 'July 26, 2026', readTime: '4 min',
                img: '',
                pinned: false
            },
            {
                slug: 'why-swollen-belly-in-your-big-dog-could-signal-heart-trouble-lilys-story',
                category: 'heart',
                title: 'Why a Swollen Belly in Your Big Dog Could Signal Heart Trouble: Lily',
                excerpt: 'When Lily',
                date: 'July 26, 2026', readTime: '4 min',
                img: '',
                pinned: false
            },
            {
                slug: 'a-9-year-old-cocker-spaniels-sudden-pot-belly-what-every-aussie-dog-owner-should-know',
                category: 'heart',
                title: 'A 9-Year-Old Cocker Spaniel',
                excerpt: 'When a Cocker Spaniel developed a pot belly, the cause was not what anyone expected. Learn about this uncommon but important heart condition.',
                date: 'July 26, 2026', readTime: '5 min',
                img: '',
                pinned: false
            }
        ,    {
      slug: 'arthritis-18-months',
      title: '18-Month Arthritis Plan',
      category: 'Arthritis',
      excerpt: 'After being diagnosed with moderate osteoarthritis at age 10, Milo has been on glucosamine, MSM and fish oil for 18 months. Full breakdown of what worked, what did not, and cost an',
      date: '05 Jul 2026', readTime: '10 min',
      img: 'https://www.agedpawwell.com/AU/_shared/assets/og-image.png',
      pinned: false
    }
    {
      slug: 'blood-in-your-senior-dogs-wee-what-it-means-for-large-breeds-like-labs-and-shepherds',
      title: 'Blood in Your Senior Dogs Wee? What It Means for Large Breeds Like Labs and Shepherds',
      category: 'Other',
      excerpt: 'Worried about dark wee or blood in your large senior dogs urine? Learn common causes, at-home checks, and when its an emergency. Plain Aussie advice for Lab, Shepherd, Rottie owner',
      date: '11 Aug 2026', readTime: '10 min',
      img: 'https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=900&q=75',
      pinned: false
    }
    {
      slug: 'daily-feeding-schedule-13-year-old-staffy',
      title: 'Complete guide: what I feed my 13-year-old staffy every single day',
      category: 'Other',
      excerpt: 'Steve shares his complete daily feeding schedule for 13-year-old Staffy. Senior kibble, sardines, chicken, glucosamine. Dog is thriving with excellent blood res',
      date: '11 Jul 2026', readTime: '10 min',
      img: '',
      pinned: false
    }
    {
      slug: 'dark-urine-or-blood-in-your-big-dogs-pee-a-mates-guide',
      title: 'Dark Urine or Blood in Your Big Dog',
      category: 'Kidney',
      excerpt: 'Noticed your senior large-breed dog',
      date: '12 Aug 2026', readTime: '10 min',
      img: 'https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=900&q=75',
      pinned: false
    }
    {
      slug: 'dark-wee-or-blood-in-your-big-old-dogs-pee-heres-what-aussie-owners-need-to-know',
      title: 'Dark Wee or Blood in Your Big Old Dogs Pee? Heres What Aussie Owners Need to Know',
      category: 'Other',
      excerpt: 'Seeing dark urine or blood in your senior large dogs wee? Learn likely causes like UTI or bladder stones, when a vet visit is urgent, and how Aussie owners can run quick at-home ch',
      date: '07 Aug 2026', readTime: '10 min',
      img: 'https://images.pexels.com/photos/7474848/pexels-photo-7474848.jpeg?auto=compress&cs=tinysrgb&w=1200',
      pinned: false
    }
    {
      slug: 'dog-back-pain-arthritis-spondylosis-early-signs',
      title: 'Back Pain & Spondylosis in Older Dogs: Early Signs Every Aussie Owner Should Know',
      category: 'Arthritis',
      excerpt: 'Understanding spinal arthritis (spondylosis) in senior dogs - symptoms, diagnosis, and management strategies for Australian pet owners.',
      date: '25 Jul 2026', readTime: '10 min',
      img: 'https://www.agedpawwell.com/AU/_shared/assets/og-image.png',
      pinned: false
    }
    {
      slug: 'dog-heart-health-mitral-valve-disease-aussie-pet-owners',
      title: 'Mitral Valve Disease in Dogs: A Guide for Australian Pet Owners',
      category: 'Heart',
      excerpt: 'Comprehensive Australian guide to mitral valve disease in dogs. Covers causes, symptoms, staging, treatment options, medication costs, and life expectancy for affected dogs.',
      date: '25 Jul 2026', readTime: '10 min',
      img: 'https://www.agedpawwell.com/AU/_shared/assets/og-image.png',
      pinned: false
    }
    {
      slug: 'dogs-recover-pulmonary-hypertension-heart-disease',
      title: 'Pulmonary Hypertension in Dogs: Understanding Diagnosis and Recovery',
      category: 'Heart',
      excerpt: 'Australian guide to pulmonary hypertension in dogs. Learn about causes, symptoms, diagnostic tests, treatment options, and what recovery looks like for affected dogs.',
      date: '25 Jul 2026', readTime: '10 min',
      img: 'https://www.agedpawwell.com/AU/_shared/assets/og-image.png',
      pinned: false
    }
    {
      slug: 'is-your-senior-large-breed-dog-hiding-pain-subtle-signs-to-check',
      title: 'Is Your Senior Large-Breed Dog Hiding Pain? Subtle Signs to Check',
      category: 'Other',
      excerpt: 'Learn to spot hidden pain in older large dogs before it worsens, with a simple at-home checklist and vet red flags.',
      date: '06 Aug 2026', readTime: '10 min',
      img: 'https://images.pexels.com/photos/1851164/pexels-photo-1851164.jpeg?w=800',
      pinned: false
    }
    {
      slug: 'large-dog-coughing-and-gagging-is-it-a-heart-problem',
      title: 'Large Dog Coughing and Gagging  Is It a Heart Problem?',
      category: 'Heart',
      excerpt: 'Could your large senior dog',
      date: '05 Aug 2026', readTime: '10 min',
      img: 'https://images.pexels.com/photos/1560807/pexels-photo-1560807.jpeg?auto=compress&cs=tinysrgb&w=800',
      pinned: false
    }
    {
      slug: 'large-dog-coughing-then-dry-heaving-could-it-be-the-heart',
      title: 'Large Dog Coughing Then Dry Heaving: Could It Be the Heart?',
      category: 'Heart',
      excerpt: 'Senior large breed dog coughs then gags like something is stuck? That choking-heave pattern can be a classic heart-disease signal. Learn what to check at home tonight, when to call',
      date: '01 Aug 2026', readTime: '10 min',
      img: 'https://images.pexels.com/photos/4587995/pexels-photo-4587995.jpeg?w=800',
      pinned: false
    }
    {
      slug: 'senior-dog-breathing-fast-heavy',
      title: 'Senior Dog Breathing Fast or Heavy: When to Worry',
      category: 'Other',
      excerpt: 'Learn how to check a senior dog',
      date: '01 Aug 2026', readTime: '10 min',
      img: 'https://images.pexels.com/photos/4587995/pexels-photo-4587995.jpeg?w=800',
      pinned: false
    }
    {
      slug: 'senior-dog-weight-loss-poor-coat-kidneys',
      title: 'Senior Dog Losing Weight and Coat Condition: Could It Be Kidneys?',
      category: 'Kidney',
      excerpt: 'Unplanned weight loss and a dull coat in a senior dog need attention. Learn when kidneys may be involved, what else can cause it and what to record for your vet.',
      date: '01 Aug 2026', readTime: '10 min',
      img: 'https://images.pexels.com/photos/5826087/pexels-photo-5826087.jpeg?w=800',
      pinned: false
    }
    {
      slug: 'senior-large-dog-coughing-and-gagging-heart-link-explained',
      title: 'Senior large dog coughing and gagging? Heart link explained',
      category: 'Heart',
      excerpt: 'If your senior Labrador or German Shepherd coughs and dry-heaves like something',
      date: '09 Aug 2026', readTime: '10 min',
      img: 'https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=900&q=75',
      pinned: false
    }
    {
      slug: 'silent-pain-in-senior-large-dogs-the-signs-they-hide-every-day',
      title: 'Silent Pain in Senior Large Dogs: The Signs They Hide Every Day',
      category: 'Other',
      excerpt: 'Many old dogs suffer pain without a whimper. Learn the subtle signs in Labradors, German Shepherds & other big breeds and try a simple at-home check tonight.',
      date: '11 Aug 2026', readTime: '10 min',
      img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=900&q=75',
      pinned: false
    }
    {
      slug: 'silent-pain-in-senior-large-dogs-why-your-labrador-doesnt-whimper',
      title: 'Silent Pain in Senior Large Dogs: Why Your Labrador Doesnt Whimper',
      category: 'Other',
      excerpt: 'Learn the subtle signs that your senior golden retriever or German shepherd may be hiding pain, and a simple at-home checklist to spot it early.',
      date: '09 Aug 2026', readTime: '10 min',
      img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=900&q=75',
      pinned: false
    }
    {
      slug: 'when-your-senior-dog-shows-no-pain-why-stoicism-doesnt-mean-comfort',
      title: 'When Your Senior Dog Shows No Pain: Why Stoicism Doesn',
      category: 'Other',
      excerpt: 'Many big dogs hide pain, even with arthritis. Learn the subtle silent signs of pain in your senior large-breed dog and how to helpno whimper needed.',
      date: '10 Aug 2026', readTime: '10 min',
      img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=900&q=75',
      pinned: false
    }
    {
      slug: 'why-is-my-senior-large-dogs-urine-dark-or-bloody-a-practical-guide-for-aussie-owners',
      title: 'Why is my senior large dogs urine dark or bloody? A practical guide for Aussie owners',
      category: 'Kidney',
      excerpt: 'Worried about dark urine or blood in your large senior dogs pee? Learn the common causes, what to check at home tonight, and when to see a vet.',
      date: '10 Aug 2026', readTime: '10 min',
      img: 'https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=900&q=75',
      pinned: false
    }
    {
      slug: 'why-your-big-old-dog-wont-tell-you-theyre-in-pain-and-how-to-help',
      title: 'Why Your Big Old Dog Wont Tell You Theyre in Pain (and How to Help)',
      category: 'Other',
      excerpt: 'Many senior large-breed dogs hide discomfort. Learn to spot the subtle signs your Labrador or German Shepherd might be quietly hurtingand when to call the vet.',
      date: '05 Aug 2026', readTime: '10 min',
      img: 'https://images.pexels.com/photos/1918290/pexels-photo-1918290.jpeg?auto=compress&cs=tinysrgb&w=800',
      pinned: false
    }
    {
      slug: 'why-your-senior-large-breed-dog-hides-pain-and-how-to-spot-it',
      title: 'Why Your Senior Large Breed Dog Hides Pain (And How to Spot It)',
      category: 'Other',
      excerpt: 'Many senior large-breed dogs hide pain. Learn the subtle signs owners miss, a simple home check, and when to see a vet. Trusted Australian advice.',
      date: '01 Aug 2026', readTime: '10 min',
      img: 'https://images.pexels.com/photos/1851164/pexels-photo-1851164.jpeg?w=800',
      pinned: false
    }
    {
      slug: 'why-your-senior-large-dog-may-be-hiding-pain-and-what-to-check-tonight',
      title: 'Why Your Senior Large Dog May Be Hiding Pain  And What to Check Tonight',
      category: 'Other',
      excerpt: 'Discover the subtle signs a senior large breed dog shows when in pain, and a simple at-home checklist to spot discomfort earlyeven when they don',
      date: '12 Aug 2026', readTime: '10 min',
      img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=900&q=75',
      pinned: false
    }
  ];




;




        




        function filterBlog(cat, btn) {




            document.querySelectorAll('.cat-btn').forEach(function(b) { b.classList.remove('active'); });




            btn.classList.add('active');




            renderGrid(cat);




        }









        function renderGrid(cat) {
            var filtered = cat === 'all' ? ARTICLES : ARTICLES.filter(function(a) {
                return a.category === cat;
            });

            var html = '';
            for (var i = 0; i < filtered.length; i++) {
                html += renderCard(filtered[i], i + 1);
            }

            document.getElementById('blogGrid').innerHTML = html || '<p style="text-align:center;padding:3rem;color:#aaa;">No articles in this category.</p>';
        }









        function renderCard(a, rank) {
            var catLabels = { "heart": "Heart", "kidney": "Kidney", "arthritis": "Arthritis", "other": "Others" };
            var label = catLabels[a.category];
