// AUTO-GENERATED by sync_blog_index.py -- do not edit by hand.
// Source of truth: AU/blog.html ARTICLES array (updated by _update_articles.py on each publish).
window.BLOG_ARTICLES = [
{
    slug: 'is-your-senior-dog-hiding-toothache-what-poppys-bad-breath-taught-her-aussie-fam',
    title: 'Is Your Senior Dog Hiding Toothache? What Poppy&#x27;s Bad Breath Taught Her Aussie Family',
    category: 'other',
    excerpt: 'Bad breath and avoiding chew toys can be signs of hidden dental pain in senior dogs. Poppy’s story shows what owners should watch for.',
    date: 'July 30, 2026',
    readTime: '6 min',
    img: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&q=75',
    pinned: false
},
{
                slug: 'is-your-senior-small-dog-coughing-at-night-its-not-just-old-age-could-be-heart',
                category: 'heart',
                title: "Is Your Senior Small Dog Coughing at Night? It's Not Just Old Age \u2013 It Could Be Their Heart",
                excerpt: "That soft, hacking cough at night could be more than old age. Learn how coughing relates to heart disease in small breed dogs.",
                date: 'July 26, 2026', readTime: '6 min',
                img: 'https://images.unsplash.com/photo-1530281700549-e82e7bf110d6?w=400&q=75',
                pinned: false
            },
{
                slug: 'your-dogs-heart-murmur-simple-bedside-checks-that-could-save-their-life',
                category: 'heart',
                title: "Your Dog&#x27;s Heart Murmur: Simple Bedside Checks That Could Save Their Life",
                excerpt: "Heart murmurs are graded 1 to 6 in dogs. Learn what each grade means, which tests to ask your vet for, and the simple checks you can do at home to monitor a murmur between visits.",
                date: 'July 29, 2026', readTime: '7 min',
                img: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&q=75',
                pinned: false
            },
{
                slug: 'heart-murmurs-and-doggy-dentals-why-your-pup-can-still-have-a-clean-pain-free-sm',
                category: 'heart',
                title: "Heart Murmurs and Doggy Dentals: Why Your Pup Can Still Have a Clean, Pain-Free Smile",
                excerpt: "Many dogs with heart murmurs still need dental work under anaesthetic. Here is how vets assess the risk, what pre-anaesthetic testing looks like, and how to keep your dog safe.",
                date: 'July 29, 2026', readTime: '5 min',
                img: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&q=75',
                pinned: false
            },
{
                slug: '7-silent-signs-senior-dog-heart-needs-check-up-what-to-do-tonight',
                category: 'heart',
                title: "7 Silent Signs Your Senior Dog's Heart Needs a Check-Up (And What to Do Tonight)",
                excerpt: "Watch for these quiet warning signs that your older dog's heart may need attention. Early detection can make all the difference.",
                date: 'July 26, 2026', readTime: '4 min',
                img: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&q=75',
                pinned: false
            },
{
                slug: 'heart-failure-in-dogs-from-silent-belly-bloat-to-deadly-blood-clots',
                category: 'heart',
                title: 'Heart Failure in Dogs: From Silent Belly Bloat to Deadly Blood Clots',
                excerpt: "One Cavalier's story reveals the subtle signs of heart failure every senior dog owner should know about before it is too late.",
                date: 'July 26, 2026', readTime: '4 min',
                img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=400&q=75',
                pinned: false
            },
{
                slug: 'your-dogs-heart-murmur-what-every-aussie-owner-needs-to-know-about-canine-heart-disease',
                category: 'heart',
                title: "Your Dog's Heart Murmur: What Every Aussie Owner Needs to Know About Canine Heart Disease",
                excerpt: "A heart murmur sounds scary, but understanding what it means can help you make the best decisions for your senior dog's care.",
                date: 'July 26, 2026', readTime: '5 min',
                img: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=400&q=75',
                pinned: false
            },
{
                slug: 'why-swollen-belly-in-your-big-dog-could-signal-heart-trouble-lilys-story',
                category: 'heart',
                title: "Why a Swollen Belly in Your Big Dog Could Signal Heart Trouble: Lily's Story",
                excerpt: "When Lily's belly swelled up, her owner had no idea it was linked to her heart. Learn what to watch for in large breed dogs.",
                date: 'July 26, 2026', readTime: '4 min',
                img: 'https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=400&q=75',
                pinned: false
            },
{
                slug: 'a-9-year-old-cocker-spaniels-sudden-pot-belly-what-every-aussie-dog-owner-should-know',
                category: 'heart',
                title: "A 9-Year-Old Cocker Spaniel's Sudden Pot Belly: What Every Aussie Dog Owner Should Know",
                excerpt: 'When a Cocker Spaniel developed a pot belly, the cause was not what anyone expected. Learn about this uncommon but important heart condition.',
                date: 'July 26, 2026', readTime: '5 min',
                img: 'https://images.unsplash.com/photo-1544568100-847a948585b9?w=400&q=75',
                pinned: false
            },
{
                slug: 'when-to-worry-about-senior-dog-stiffness',
                category: 'arthritis',
                title: "When to Worry About Your Senior Dog Stiffness",
                excerpt: "Occasional stiffness after a long walk or a cold night is common in senior dogs and often eases with a little rest. But some signs should never be...",
                date: 'July 27, 2026', readTime: '4 min',
                img: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&q=75',
                pinned: false
            },
{
                slug: 'early-signs-joint-pain-dogs-how-to-help-your-aussie-mate-stay-active',
                category: 'arthritis',
                title: "Early Signs of Joint Pain in Dogs and How to Help Your Aussie Mate Stay Active",
                excerpt: "Occasional stiffness after a long walk or a cold night is common in senior dogs and often eases with a little rest. But some signs should never be ignored.",
                date: 'July 27, 2026', readTime: '4 min',
                img: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?w=400&q=75',
                pinned: false
            },
{
                slug: 'when-your-senior-dog-needs-the-vet-for-arthritis',
                category: 'arthritis',
                title: "When Your Senior Dog Needs the Vet for Arthritis",
                excerpt: "Occasional stiffness may improve with rest, but certain signs should never be ignored. Learn when arthritis warrants a vet visit.",
                date: 'July 27, 2026', readTime: '4 min',
                img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&q=75',
                pinned: false
            },
{
                slug: 'increased-thirst-and-urination-early-signs-canine-kidney-disease',
                category: 'kidney',
                title: "Is Your Senior Dog Drinking More Water Than Usual? Early Kidney Disease Signs",
                excerpt: "Excessive thirst and frequent urination are the most common early signs of chronic kidney disease in senior dogs — yet they're also the easiest to dismiss. Here's what every Australian dog owner needs to know.",
                date: 'July 27, 2026', readTime: '5 min',
                img: 'https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&q=75',
                pinned: false
            },
{
                slug: 'kidney-disease-senior-dogs-diet-treatment-complete-guide',
                category: 'kidney',
                title: "Kidney Disease in Senior Dogs: Your Complete Guide to Diet, Treatment & Survival",
                excerpt: "A diagnosis of chronic kidney disease does not mean giving up. With the right prescription diet, medical management, and regular monitoring, many senior dogs live comfortably for years. Here's everything you need to know.",
                date: 'July 27, 2026', readTime: '5 min',
                img: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?w=400&q=75',
                pinned: false
            },
{
                slug: 'kidney-biopsy-in-dogs-what-it-reveals-and-why-it-matters',
                category: 'kidney',
                title: "Kidney Biopsy in Dogs: What It Reveals and Why It Changes Treatment",
                excerpt: "A kidney biopsy can identify the exact type of kidney disease your dog has — and that information directly determines whether to use immunosuppression, kidney protection, or both. New data from 1,439 canine biopsies explains why it matters.",
                date: 'July 27, 2026', readTime: '5 min',
                img: 'https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?w=400&q=75',
                pinned: false
            }
,
{
                slug: 'why-your-senior-dog-coughs-at-night-heart-or-just-a-hack',
                category: 'heart',
                title: 'Why Your Senior Dog Coughs at Night: Heart or Just a Hack?',
                excerpt: "A night cough in your large senior dog can be a red flag for heart trouble. Learn when to worry, home comfort tips, and how to count sleeping breaths in plain Aussie English.",
                date: 'July 31, 2026', readTime: '6 min',
                img: 'https://images.unsplash.com/photo-1586671267731-da2cf3ceeb80?w=900&q=75',
                pinned: false
            },
{
                slug: 'what-chronic-kidney-disease-in-large-breeds-really-means-and-why-its-not-kidney-failure',
                category: 'kidney',
                title: 'What Chronic Kidney Disease in Large Breeds Really Means (And Why It\'s Not \'Kidney Failure\')',
                excerpt: "A warm, chatty guide for Aussie owners: CKD is a staged condition, not immediate kidney failure. Learn what abnormal kidney values really mean and how to help your big dog.",
                date: 'July 31, 2026', readTime: '5 min',
                img: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=900&q=75',
                pinned: false
            },
{
                slug: 'dog-cough-heart-or-airway-5-clues-to-record-for-your-vet',
                category: 'heart',
                title: 'Dog Cough: Heart or Airway? 5 Clues to Record for Your Vet',
                excerpt: "Learn to tell if your senior large breed dog's cough is from the heart or lungs. Simple at-home clues on timing, sound, and triggers to note before the vet visit.",
                date: 'July 31, 2026', readTime: '5 min',
                img: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=900&q=75',
                pinned: false
            },
{
                slug: 'your-senior-dogs-joint-map-hip-elbow-knee-spinewhats-really-going-on',
                category: 'arthritis',
                title: 'Your Senior Dogs Joint Map: Hip, Elbow, Knee & SpineWhats Really Going On',
                excerpt: "Learn how different large-breed joint spots (hip, knee, elbow, spine) can show up, from a quiet hip sway to morning stiffness, and simple at-home checks you can do tonight.",
                date: 'July 31, 2026', readTime: '6 min',
                img: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?w=900&q=75',
                pinned: false
            },
{
                slug: 'why-is-my-big-old-dog-suddenly-not-moving-personality-or-pain',
                category: 'Kidney',
                title: 'Why Is My Big Old Dog Suddenly Not Moving? Personality or Pain?',
                excerpt: "A big old dog that's suddenly lying down all day might be more than lazy. Discover the top reasons and what to check at home tonight.",
                date: 'August 01, 2026', readTime: '6 min',
                img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=900&q=75',
                pinned: false
            },
{
                slug: 'senior-large-dog-suddenly-wont-move-read-this-nononsense-checklist-now',
                category: 'Heart',
                title: 'Senior Large Dog Suddenly Won\'t Move? Read This NoNonsense Checklist Now',
                excerpt: "If your large senior dog has suddenly stopped wanting to walk, its likely a health issue, not laziness. Learn the warning signs and when to see a vet.",
                date: 'August 01, 2026', readTime: '5 min',
                img: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=900&q=75',
                pinned: false
            },
{
                slug: 'why-your-large-dogs-bad-breath-and-mouth-sores-might-mean-kidney-worry',
                category: 'Kidney',
                title: 'Why Your Large Dogs Bad Breath and Mouth Sores Might Mean Kidney Worry',
                excerpt: "Worsening breath and mouth ulcers in a senior large-breed dog could point to kidney trouble. Learn the signs, what to check at home, and when to call the vet.",
                date: 'August 01, 2026', readTime: '6 min',
                img: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=900&q=75',
                pinned: false
            },
{
                slug: 'purple-gums-in-big-dogs-a-no-nonsense-guide-for-senior-large-breeds',
                category: 'Heart',
                title: 'Purple Gums in Big Dogs: A No-Nonsense Guide for Senior Large Breeds',
                excerpt: "Purple or blue gums in a Labrador, Rottweiler, or other large breed can signal a heart emergency. Learn what causes it, how to check at home, and when to go to the vet right away.",
                date: 'August 01, 2026', readTime: '5 min',
                img: 'https://images.unsplash.com/photo-1518717758536-85ae29035b6d?w=900&q=75',
                pinned: false
            },
{
                slug: 'your-senior-dogs-limp-more-than-arthritis-a-guide-for-large-breeds',
                category: 'Arthritis',
                title: 'Your Senior Dogs Limp: More Than Arthritis? A Guide for Large Breeds',
                excerpt: "A limp isnt always arthritis in older large breeds. Learn what else could be causing it, when to worry, and simple at-home checks you can do tonight.",
                date: 'August 01, 2026', readTime: '6 min',
                img: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?w=900&q=75',
                pinned: false
            }];
